// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsavel pela carteira do cliente. Vendedores desligados nao aparecem. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Posicao do cliente dentro da fila DAQUELE vendedor, do maior score para o menor. Comece pelo 1. */
          ordem: number;
          /** Identificador do cliente no catalogo. */
          cliente_id: number;
          /** Nome do cliente, como falar com ele. */
          razao_social: string;
          /** Cidade do cliente. */
          cidade: string;
          /** Estado do cliente. */
          uf: string;
          /** Nome do vendedor responsavel pela carteira do cliente. Vendedores desligados nao aparecem. */
          vendedor: string;
          /** Probabilidade estimada de o cliente comprar nos proximos 7 dias, de 0 a 1. Vem do modelo propensao_compra. */
          score: number;
          /** Faixa do score: Fria, Morna, Quente ou Muito quente. Serve para conversar sem citar numero. */
          faixa: string;
          /** Valor medio dos pedidos deste cliente, em reais. Ajuda a dimensionar a oferta. */
          ticket_medio: number;
          /** Por que este cliente esta na fila, em portugues e com os numeros dele. E o que faz o vendedor confiar quando o modelo acerta e entender quando erra. */
          motivo: string;
          /** O que oferecer: o SKU mais comprado na marca preferida do cliente que ele parou de comprar nos ultimos 90 dias, com o saldo do snapshot mais recente. */
          sugestao: string;
          /** Resultado da ligacao. Valores possiveis: vendeu, vai_pensar, sem_interesse, nao_atendeu. Só `vendeu` conta como conversao. */
          retorno_status: string;
          /** Texto livre do vendedor sobre a conversa. Pode ser nulo. */
          retorno_comentario: string;
          /** Quando o retorno foi registrado. Um cliente pode ter varios retornos: para o estado atual, use o mais recente por esta coluna. */
          retorno_em: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** @sqlType BIGINT */
          versao: number;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsavel pela carteira do cliente. Vendedores desligados nao aparecem. */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
